keidarcy/e1s

- README.md
- api/auto_scaling.go
- api/cluster.go
- main.go
- ui/app.go
- ui/cluster.go
- ui/components.go
- ui/container.go
- ui/json.go
- ui/modal.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/view.go
https://github.com/keidarcy/e1s/issues/89
Add `r` key to reload current resources
> Support reload resources

- ui/json.go
- ui/kind.go
- ui/list.go
- ui/service.go
- ui/table.go
- ui/view.go
Show service events in list not json
> feat: show service event in list content view

- ui/components.go
- ui/kind.go
- ui/table.go
- ui/view.go
in browser environment esc is exit text area, add ctrl+z for back
> feat: add ctrl z for back

- README.md
- api/auto_scaling.go
- api/cluster.go
- api/logs.go
- api/metrics.go
- api/service.go
- api/store.go
- api/task.go
- api/task_definition.go
- go.mod
- go.sum
- main.go
- ui/app.go
- ui/cluster.go
- ui/json.go
- ui/list.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/view.go
- util/util.go
https://github.com/keidarcy/e1s/issues/135
> chore: use logrus logger

- api/service.go
- ui/modal.go
https://github.com/keidarcy/e1s/issues/145
> feat: support CODE_DEPLOY service update

- ui/app.go
- ui/cluster.go
- ui/container.go
- ui/service.go
- ui/task.go
- ui/view.go
https://github.com/keidarcy/e1s/issues/144
> feat: reload persist table row index

- main.go
- ui/app.go
- ui/cluster.go
- ui/components.go
- ui/container.go
- ui/json.go
- ui/json_test.go
- ui/kind.go
- ui/list.go
- ui/modal.go
- ui/notice.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/view.go
- util/util.go
https://github.com/keidarcy/e1s/issues/134
> feat: show feedback on footer

- .gitignore
- README.md
- api/ssm.go
- go.mod
- go.sum
- main.go
- ui/app.go
- ui/components.go
- ui/container.go
- ui/json.go
- ui/list.go
- ui/modal.go
- ui/port_forwarding.go
- ui/table.go
- ui/view.go
- util/util.go
- **feat: use cobra parse input**
- **add log format json support**
- **show version with latest version**
- **support terminate port forwarding session**
https://github.com/keidarcy/e1s/issues/163
https://github.com/keidarcy/e1s/issues/162
> feat: use cobra parse input and support terminate port forwarding session

- README.md
- main.go
- ui/app.go
- ui/cluster.go
- ui/container.go
- ui/json.go
- ui/json_test.go
- ui/kind.go
- ui/list.go
- ui/modal.go
- ui/port_forwarding.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/view.go
https://github.com/keidarcy/e1s/issues/144
- **fix options and readme**
- **add ticker to refresh**
> feat: add auto refresh data option

- .goreleaser.yml
- ui/modal.go
- ui/port_forwarding.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/view.go
- util/util.go
- **feat: show failures in task**
- **chore: adjust item in service and task**
> chore: adjust item in service and task

- README.md
- api/service.go
- api/task_definition.go
- ui/app.go
- ui/cluster.go
- ui/container.go
- ui/footer.go
- ui/json.go
- ui/json_test.go
- ui/kind.go
- ui/list.go
- ui/service.go
- ui/table.go
- ui/task.go
- ui/task_definition.go
- ui/view.go
- util/util.go
- util/util_test.go
- **feat: support better task definition**
- **fix describe**
- **show more task definition items**
> feat: support better task definition

- tests/ec2-ecs.tf
- tests/ecs.tf
- ui/kind.go
- ui/table.go
- ui/task_definition.go
https://github.com/keidarcy/e1s/issues/85
> feat: add ecs on ec2 tf

- README.md
- main.go
- ui/app.go
- ui/container.go
- ui/view.go
https://github.com/keidarcy/e1s/issues/178
> feat: support custom ecs exec ssh shell

- README.md
- internal/api/task.go
- internal/utils/utils.go
- internal/view/app.go
- internal/view/cluster.go
- internal/view/header.go
- internal/view/json.go
- internal/view/modal.go
- internal/view/service.go
- internal/view/table.go
- internal/view/task.go
- internal/view/task_definition.go
- internal/view/view.go
- tests/ecs.tf
- tests/features.tf
- tests/outputs.tf
- tests/variables.tf
https://github.com/keidarcy/e1s/issues/85
> feat: support show tasks from cluster

- README.md
- internal/api/task.go
- internal/api/task_definition.go
- internal/view/app.go
- internal/view/container.go
- internal/view/header.go
- internal/view/service.go
- internal/view/table.go
- internal/view/task.go
- internal/view/task_definition.go
- **feat: support show pending or stopped tasks**
- **update readme**
> feat: support show pending or stopped tasks

- .gitignore
- internal/api/cluster.go
- internal/api/service.go
https://github.com/keidarcy/e1s/issues/226
> feat: support more than 100 clusters

- README.md
- cmd/e1s/main.go
- internal/view/app.go
- internal/view/help.go
- **feat: add cluster option**
- **allow back when specified cluster**
- **update readme**
https://github.com/keidarcy/e1s/issues/226
> feat: add cluster option

- README.md
- internal/api/logs.go
- internal/color/fmt.go
- internal/view/app.go
- internal/view/cluster.go
- internal/view/container.go
- internal/view/header.go
- internal/view/list.go
- internal/view/modal.go
- internal/view/table.go
- internal/view/task.go
- internal/view/view.go
https://github.com/keidarcy/e1s/issues/256
https://github.com/keidarcy/e1s/issues/271
> feat: add container logs

- README.md
- internal/ui/modal.go
- internal/view/header.go
- internal/view/help.go
- internal/view/modal.go
- internal/view/search.go
- internal/view/table.go
- internal/view/view.go
Allows to make search on any table, using the forward slash.
Functionality similar to vim / less pager
> feat: search in table

- README.md
- internal/api/service_deployment.go
- internal/utils/utils.go
- internal/view/app.go
- internal/view/footer.go
- internal/view/header.go
- internal/view/json.go
- internal/view/kind.go
- internal/view/service.go
- internal/view/service_deployment.go
- internal/view/table.go
- internal/view/task_definition.go
https://aws.amazon.com/about-aws/whats-new/2024/11/service-versioning-deployment-history-amazon-ecs-services/
Support service deployment `p` in service page
> feat: support service deployment api

- internal/api/task.go
Addresses https://github.com/keidarcy/e1s/issues/344
> fix crash when listing stopped tasks for whole cluster

- internal/view/header.go
- internal/view/help.go
https://github.com/keidarcy/e1s/issues/342
> docs: add field next previous
